const SHOW_RESOURCES = "SHOW_RESOURCES";

const GET_RESOURCES_REQUEST = "GET_RESOURCES_REQUEST";
const GET_RESOURCES_SUCCESS = "GET_RESOURCES_SUCCESS";
const GET_RESOURCES_ERROR = "GET_RESOURCES_ERROR";
